navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon:
    title:
  menu:
    - name: åšå®¢
      icon: fas fa-rss
      url: /
    - name: åˆ†ç±»
      icon: fas fa-folder-open
      url: categories/
    - name: æ ‡ç­¾
      icon: fas fa-tags
      url: tags/
    - name: å½’æ¡£
      icon: fas fa-archive
      url: archives/
    - name: å‹é“¾
      icon: fas fa-link
      url: friends/
    - name: å…³äº
      icon: fas fa-info-circle
      url: about/
  search: è¾“å…¥å…³é”®è¯...   # Search bar placeholder

cover:
  height_scheme: full # full, half
  layout_scheme: search # blank (ç•™ç™½), search (æœç´¢), dock (å), featured (ç²¾é€‰), focus (ç„¦ç‚¹)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  background: https://img.vim-cn.com/6d/a0c9e6f9efad8b731cb7376504bd10d79d2053.jpg
  # background: https://i0.hdslb.com/bfs/album/a3ac63512142706c657e8bcedb8ffdaf4d713315.png
  logo:
  title: SilenHub
  subtitle: 'åƒé¥­, ç¡è§‰, æ‰“æ¸¸æˆ!'
  search: è¾“å…¥å…³é”®è¯æŸ¥æ‰¾... # search bar placeholder
  features:
    - name: åšå®¢å½’æ¡£
      icon: fas fa-archive
      img: #
      url: /archives/
    - name: æŠ€èƒ½æ‰‹å†Œ
      icon: fas fa-book
      img: #
      url: /handbook/
    - name: ä¸»é¢˜æºç 
      icon: fab fa-github
      img: #
      url: https://github.com/volantis-x/hexo-theme-volantis/

sidebar:
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://avatars.githubusercontent.com/u/12797055?s=460&u=7de48cdd15f6aadddefe92a0dfbcc70fc82bac05&v=4
      shape: circle # circle, rectangle
      url: /about/
      title:
      subtitle:
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social:
        - icon: fas fa-envelope
          url: mailto:qiumin14@163.com
        - icon: fab fa-github
          url: https://github.com/SilenWang/


pages:
  # å‹é“¾é¡µé¢é…ç½®
  friends:
    layout_scheme: simple # simple: ç®€å•å¸ƒå±€, traditional: ä¼ ç»Ÿå¸ƒå±€,  sites: ç½‘ç«™å¡ç‰‡å¸ƒå±€

############################### Color Scheme ############################### > start
color_scheme:
  # ------------
  # é€šç”¨é¢œè‰²
  common:
    # ä¸»é¢˜è‰²
    theme: '#1BC3FB'
    # é“¾æ¥è‰²
    link: '#2196f3'
    # æŒ‰é’®è‰²
    button: '#1BC3FB'
    # é¼ æ ‡æ”¾åˆ°äº¤äº’å…ƒç´ ä¸Šæ—¶çš„è‰²
    hover: '#ff5722'
    # ä¸»é¢˜è‰²å—å†…éƒ¨çš„æ–‡å­—é¢œè‰²
    inner: '#fff'
    # é€‰ä¸­åŒºåŸŸæ–‡å­—çš„èƒŒæ™¯é¢œè‰²
    selection: 'alpha(#2196f3, 0.2)'
  # ------------
  # äº®è‰²ä¸»é¢˜ï¼ˆé»˜è®¤ï¼‰
  light:
    # ç½‘ç«™èƒŒæ™¯è‰²
    site_bg: '#f4f4f4'
    # ç½‘ç«™èƒŒæ™¯ä¸Šçš„æ–‡å­—
    site_inner: '#444'
    # ç½‘ç«™é¡µè„šæ–‡å­—
    site_footer: '#666'

    # å¡ç‰‡èƒŒæ™¯è‰²
    card: '#fff'
    # å¡ç‰‡ä¸Šçš„æ™®é€šæ–‡å­—
    text: '#444'

    # åŒºå—å’Œä»£ç å—èƒŒæ™¯è‰²
    block: '#f6f6f6'
    # ä»£ç å—é«˜äº®æ—¶çš„èƒŒæ™¯è‰²
    codeblock: '#FFF7EA'
    # è¡Œå†…ä»£ç é¢œè‰²
    inlinecode: '#c74f00'

    # æ–‡ç« éƒ¨åˆ†
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'

    # åˆ—è¡¨æ–‡å­—
    list: '#666'
    # åˆ—è¡¨ hover æ—¶çš„æ–‡å­—
    list_hl: 'mix($color-theme, #000, 80)'
    # è¾…åŠ©æ€§æ–‡å­—
    meta: '#888'
  # ------------
  # æš—è‰²ä¸»é¢˜
  dark:
    # ç½‘ç«™èƒŒæ™¯è‰²
    site_bg: '#222'
    # ç½‘ç«™èƒŒæ™¯ä¸Šçš„æ–‡å­—
    site_inner: '#eee'
    # ç½‘ç«™é¡µè„šæ–‡å­—
    site_footer: '#aaa'
    # å¡ç‰‡èƒŒæ™¯è‰²
    card: '#333'
    # å¡ç‰‡ä¸Šçš„æ™®é€šæ–‡å­—
    text: '#eee'

    # åŒºå—å’Œä»£ç å—èƒŒæ™¯è‰²
    block: '#3a3a3a'
    # ä»£ç å—é«˜äº®æ—¶çš„èƒŒæ™¯è‰²
    codeblock: '#343a3c'
    # è¡Œå†…ä»£ç é¢œè‰²
    inlinecode: '#D56D28'

    # æ–‡ç« éƒ¨åˆ†
    h1: '#eee'
    h2: '#eee'
    h3: '#ddd'
    h4: '#ddd'
    h5: '#ddd'
    h6: '#ddd'
    p: '#bbb'

    # åˆ—è¡¨æ–‡å­—
    list: '#aaa'
    # åˆ—è¡¨ hover æ—¶çš„æ–‡å­—
    list_hl: 'mix($color-theme, #fff, 80)'
    # è¾…åŠ©æ€§æ–‡å­—
    meta: '#888'
    # å¤œé—´å›¾ç‰‡äº®åº¦
    brightness: 70%
############################### Color Scheme ############################### > end

comments:
  title: <i class='fas fa-comments'></i> è¯„è®º
  subtitle: ç•™ä¸‹å‹å–„çš„è¯„è®ºå§~
  service: utterances
  utterances:
    repo: SilenWang/silenwang.github.io
    issue-term: pathname
    issue-number:
    theme:
      light: github-light
      dark: github-dark
    label: âœ¨ğŸ’¬âœ¨

article:
  body:
    meta_library:
      author:
        avatar: https://avatars.githubusercontent.com/u/12797055?s=60&v=4
        name: Sylen Wong
        url: /


plugins:
  busuanzi: 
    enable: true

analytics:
  busuanzi: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
#   leancloud: # è¯·ä½¿ç”¨è‡ªå·±çš„ id & key ä»¥é˜²æ­¢æ•°æ®ä¸¢å¤±
#     app_id: 1AHzGaS0YK78EJ9GeLGiS7mA-gzGzoHsz #u9j57bwJod4EDmXWdxrwuqQT-MdYXbMMI
#     app_key: SUIANMoyA6DBqnztrnls7s7K #jfHtEKVE24j0IVCGHbvuFClp
#     # custom_api_server: # å›½é™…ç‰ˆä¸€èˆ¬ä¸éœ€è¦å†™ï¼Œé™¤éè‡ªå®šä¹‰äº† API Server


site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [social, license, analytics, info, copyright]
  copyright: 'Copyright Â© 2016-Now Sylen Wong'